development:
  adapter: postgresql
  encoding: unicode
  database: ol2_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ol2_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ol2_production
  pool: 5