development:
  adapter: postgresql
  encoding: unicode
  database: openlectures_development
  pool: 5
  username: openlectures
  password: openlectures

test:
  adapter: postgresql
  encoding: unicode
  database: openlectures_test
  pool: 5
  username: openlectures
  password: openlectures

production:
  adapter: postgresql
  encoding: unicode
  database: openlectures_production
  pool: 5
  username: openlectures
  password: openlectures
